### PR TITLE
Electron 1.3.3

### PR DESCRIPTION
**Pull request by CarlQLange**
Something's broken with the electron-rebuild package though. 😢 sadly I have exactly zero idea of what it might be. This works, but probably won't fully function for proper apps.

### CODE REVIEW

**Comment by wallynm** [comment]
I was so happy to see this PR, the rebuild process isn't working?
i will try to update and see what happens!

**Comment by CarlQLange** [comment]
Some of it's working, but [this](https://github.com/electron/electron-rebuild/issues/9) is happening when you uncomment [this](https://github.com/electron-webapps/meteor-electron/pull/96/commits/abacc34e9bb46056505d5c03a1a4fd04d8ccb9c0#diff-7949dd4dfa2376494b16adbd4db11134R152).

**Comment by menelike** [comment]
I got it working on the latest Electron (1.3.5) including some other PR and fixes.
Runs stable on OSX. If it works well for you we could switch to a new PR.

https://github.com/risetechnologies/meteor-electron

_master branch is still under development_

**Comment by CarlQLange** [comment]
👍 I don't mind! I don't really use Electron, so someone else should probably check it out. I'm happy to close this or have it closed in favour of a PR that knows what it's doing :)

**Comment by menelike** [comment]
FYI: We rewrote everything to `electron-builder`, see https://github.com/electron-webapps/meteor-electron/issues/104
We currently prefer a permanent fork as we're not sure if this project is still maintained. A PR _might_ follow in the future.

**Comment by CarlQLange** [comment]
¯\_(ツ)_/¯ gonna close this, I expect that at this point there's a better way to do this and this project appears unmaintained. Have a good day everyone!

**Pull request closed without merging**
